### ISSUE TITLE
change the output audiocodec 

### ISSUE THREAD

**Issue by AGPonomarev** [C0D3D3V/bbb-dl#10]
Add the ability to change the output audiocodec

**Comment by C0D3D3V** [comment]
Sounds like a good feauture, might you want to try implementing it and doing a PullRequest?

**Comment by AGPonomarev** [comment]
Can this be done via ffmpeg? I'll try, but it won't be fast.

**Comment by C0D3D3V** [comment]
In principle the audio codec is controlled in the function `mux_slideshow_with_webcam` and `mux_slideshow`. In both cases, I just copy the codec from the original source with the parameter `-c:a`. To convert it to a different codec, you have to change this parameter.
