### ISSUE TITLE
WARNING: [BBB] Final Slideshow already exists. Abort!

### ISSUE THREAD

**Issue by persuader** [C0D3D3V/bbb-dl#14]
Hi i am trying to convert some bbb recording to video and get the following error. 

[BBB] Concat Slideshow
frame=264461 fps=28555 q=-1.0 Lsize=  212623kB time=03:03:39.16 bitrate= 158.1kbits/s speed=1.19e+03x
[BBB] Mux Slideshow
WARNING: [BBB] Final Slideshow already exists. Abort!

So no video is produced. Any ideas how to fix this ?

This is the link to the presentation - [https://bbb.gateway.bg/playback/presentation/2.0/playback.html?meetingId=fe1e832a5e0901f6875428091156b69c4cf9d975-1593669442361](url)

Thanks in advance.

**Comment by C0D3D3V** [comment]
What parameters did you set? Did you clean up the download folder?

**Comment by persuader** [comment]
Yes the download folder is cleaned. The command is.
`bbb-dl https://bbb.gateway.bg/playback/presentation/2.0/playback.html?meetingId=fe1e832a5e0901f6875428091156b69c4cf9d975-1593669442361 -aw -aa -ncc -f Aktualni_aspekti_na_politikata_po_zaetostta_v_konteksta_na__povishavane__kachestvoto_na_rabotnata_sila20200702_085722.mp4`

**Comment by C0D3D3V** [comment]
https://github.com/C0D3D3V/bbb-dl/blob/3498bafdbbe0173b356be244f61634282f1eeb45/bbb_dl/main.py#L217-L227

As you can see in line 226, the error message only occurs if the result file already exists, so you must delete or move the "`Aktualni_aspekti_na_politikata_po_zaetostta_v_konteksta_na__povishavane__kachestvoto_na_rabotnata_sila20200702_085722.mp4`" file.

**Comment by C0D3D3V** [comment]
Since I have just created the video itself, I could upload it to you :D. But if the file already exists, then you have probably already downloaded (rendered) the video itself. By the way, I would recommend to set the option `-kt`, if you want to change something after the program is finished (like activating the webcam) then you can do that without downloading and rendering all files again.

**Comment by persuader** [comment]
Hi. 10x for the quick response. I am sure i was deleting the temp files dir AND check for the current filename but after checking again and deleteing it the process is ok. I have another issue with another video (i must convert about 200 presentations) Can i post here or better open another issue.

**Comment by C0D3D3V** [comment]
The error log would be more helpful than the link itself but feel free to send both here.

**Comment by persuader** [comment]
command - bbb-dl -v http://bbb.gateway.bg/playback/presentation/2.0/playback.html?meetingId=8902e242809bc05674ac6185e85d341d30e428bd-1620201672416 -aw -aa -ncc -f Sotsialna_rabota_s_litsa_i_semeistva_v_risk20210505_110112.mp4

result - 

[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-147-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 4.3.2-0york0, ffprobe 4.3.2-0york0
[debug] Proxy map: {}
[BBB] Downloading meta informations
[BBB] 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416: Downloading webpage
[BBB] 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416: Downloading XML
[BBB] 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416: Downloading XML
[BBB] 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416: Downloading XML
[BBB] BBB version: 3.8.7
[BBB] Downloading slides
[BBB] Downloading slide slide-000.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-000.png
[BBB] Downloading slide slide-001.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-001.png
[BBB] Downloading slide deskshare.webm...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/deskshare.webm
[BBB] Slide slide-001.png is already present
[BBB] Downloading slide slide-002.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-002.png
[BBB] Slide slide-001.png is already present
[BBB] Slide slide-002.png is already present
[BBB] Slide deskshare.webm is already present
[BBB] Slide slide-002.png is already present
[BBB] Downloading slide slide-003.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-003.png
[BBB] Downloading slide slide-004.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-004.png
[BBB] Slide slide-003.png is already present
[BBB] Slide slide-002.png is already present
[BBB] Slide slide-001.png is already present
[BBB] Slide slide-002.png is already present
[BBB] Slide slide-003.png is already present
[BBB] Slide slide-004.png is already present
[BBB] Slide deskshare.webm is already present
[BBB] Slide slide-004.png is already present
[BBB] Downloading slide slide-005.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-005.png
[BBB] Downloading slide slide-006.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-006.png
[BBB] Downloading slide slide-007.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-007.png
[BBB] Downloading slide slide-008.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-008.png
[BBB] Slide slide-007.png is already present
[BBB] Slide slide-008.png is already present
[BBB] Slide slide-007.png is already present
[BBB] Slide slide-006.png is already present
[BBB] Slide slide-005.png is already present
[BBB] Slide slide-006.png is already present
[BBB] Slide slide-007.png is already present
[BBB] Slide slide-008.png is already present
[BBB] Downloading slide slide-009.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-009.png
[BBB] Downloading slide slide-010.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-010.png
[BBB] Downloading slide slide-011.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-011.png
[BBB] Downloading slide slide-012.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-012.png
[BBB] Downloading slide slide-013.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-013.png
[BBB] Downloading slide slide-014.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-014.png
[BBB] Downloading slide slide-015.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-015.png
[BBB] Downloading slide slide-016.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-016.png
[BBB] Downloading slide slide-017.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-017.png
[BBB] Downloading slide slide-018.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-018.png
[BBB] Downloading slide slide-019.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-019.png
[BBB] Downloading slide slide-020.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-020.png
[BBB] Downloading slide slide-021.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-021.png
[BBB] Downloading slide slide-022.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-022.png
[BBB] Downloading slide slide-023.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-023.png
[BBB] Downloading slide slide-024.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-024.png
[BBB] Downloading slide slide-025.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-025.png
[BBB] Downloading slide slide-026.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-026.png
[BBB] Downloading slide slide-027.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-027.png
[BBB] Downloading slide slide-028.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-028.png
[BBB] Downloading slide slide-029.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-029.png
[BBB] Downloading slide slide-030.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-030.png
[BBB] Downloading slide slide-031.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-031.png
[BBB] Slide slide-030.png is already present
[BBB] Downloading slide slide-032.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-032.png
[BBB] Downloading slide slide-033.png...
[BBB] Successfully downloaded to: 8902e242809bc05674ac6185e85d341d30e428bd-1620201672416/slide-033.png
[BBB] Paint image slide-002.png with annotation 5/49 (Frame: 6/56)
[BBB] Paint image slide-002.png with annotation 12/49 (Frame: 6/56)
[BBB] Paint image slide-002.png with annotation 13/49 (Frame: 6/56)
[BBB] Paint image slide-002.png with annotation 17/49 (Frame: 6/56)
[BBB] Paint image slide-002.png with annotation 25/49 (Frame: 6/56)
[BBB] Paint image slide-002.png with annotation 30/49 (Frame: 6/56)
[BBB] Paint image slide-002.png with annotation 34/49 (Frame: 6/56)
[BBB] Paint image slide-002.png with annotation 42/49 (Frame: 6/56)
[BBB] Paint image slide-002.png with annotation 49/49 (Frame: 6/56)
[BBB] Paint image slide-002.png with annotation 4/55 (Frame: 8/56)
[BBB] Paint image slide-002.png with annotation 6/55 (Frame: 8/56)
[BBB] Paint image slide-002.png with annotation 16/55 (Frame: 8/56)
[BBB] Paint image slide-002.png with annotation 21/55 (Frame: 8/56)
[BBB] Paint image slide-002.png with annotation 22/55 (Frame: 8/56)
[BBB] Paint image slide-002.png with annotation 24/55 (Frame: 8/56)
[BBB] Paint image slide-002.png with annotation 34/55 (Frame: 8/56)
[BBB] Paint image slide-002.png with annotation 38/55 (Frame: 8/56)
[BBB] Paint image slide-002.png with annotation 40/55 (Frame: 8/56)
[BBB] Paint image slide-002.png with annotation 48/55 (Frame: 8/56)
[BBB] Paint image slide-002.png with annotation 49/55 (Frame: 8/56)
[BBB] Paint image slide-002.png with annotation 53/55 (Frame: 8/56)
[BBB] Paint image slide-002.png with annotation 55/55 (Frame: 8/56)
[BBB] Paint image slide-003.png with annotation 0/35 (Frame: 9/56)
[BBB] Paint image slide-003.png with annotation 7/35 (Frame: 9/56)
[BBB] Paint image slide-003.png with annotation 8/35 (Frame: 9/56)
[BBB] Paint image slide-003.png with annotation 11/35 (Frame: 9/56)
[BBB] Paint image slide-003.png with annotation 19/35 (Frame: 9/56)
[BBB] Paint image slide-003.png with annotation 22/35 (Frame: 9/56)
[BBB] Paint image slide-003.png with annotation 28/35 (Frame: 9/56)
[BBB] Paint image slide-003.png with annotation 34/35 (Frame: 9/56)
[BBB] Paint image slide-003.png with annotation 35/35 (Frame: 9/56)
[BBB] Paint image slide-004.png with annotation 4/36 (Frame: 10/56)
[BBB] Paint image slide-004.png with annotation 13/36 (Frame: 10/56)
[BBB] Paint image slide-004.png with annotation 21/36 (Frame: 10/56)
[BBB] Paint image slide-004.png with annotation 22/36 (Frame: 10/56)
[BBB] Paint image slide-004.png with annotation 27/36 (Frame: 10/56)
[BBB] Paint image slide-004.png with annotation 35/36 (Frame: 10/56)
[BBB] Paint image slide-004.png with annotation 36/36 (Frame: 10/56)
[BBB] Paint image slide-003.png with annotation 3/3 (Frame: 11/56)
[BBB] Paint image slide-002.png with annotation 8/8 (Frame: 12/56)
[BBB] Paint image slide-002.png with annotation 8/8 (Frame: 14/56)
[BBB] Paint image slide-003.png with annotation 3/3 (Frame: 15/56)
[BBB] Paint image slide-004.png with annotation 1/1 (Frame: 16/56)
[BBB] Paint image slide-004.png with annotation 1/1 (Frame: 18/56)
[BBB] Paint image slide-005.png with annotation 0/124 (Frame: 19/56)
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1481, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [Errno 2] No such file or directory: '/bbb_rec/rec/presentation/6aa8ceb30c01be66d7b7474c29c9688c65e66c2b-1620204828346/poll_result16.svg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bbb-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/bbb_dl/main.py", line 723, in main
    args.filename,
  File "/usr/local/lib/python3.6/dist-packages/bbb_dl/main.py", line 175, in run
    slides_infos = self._add_annotations(slides_infos)
  File "/usr/local/lib/python3.6/dist-packages/bbb_dl/main.py", line 333, in _add_annotations
    self.convert_svg_to_png(ElementTree.tostring(svg_root), slide.width, slide.height, new_path)
  File "/usr/local/lib/python3.6/dist-packages/bbb_dl/main.py", line 626, in convert_svg_to_png
    write_to=open(output_path, 'wb'),
  File "/usr/local/lib/python3.6/dist-packages/cairosvg/surface.py", line 135, in convert
    map_image=invert_image if invert_images else None)
  File "/usr/local/lib/python3.6/dist-packages/cairosvg/surface.py", line 223, in __init__
    self.draw(tree)
  File "/usr/local/lib/python3.6/dist-packages/cairosvg/surface.py", line 469, in draw
    self.draw(child)
  File "/usr/local/lib/python3.6/dist-packages/cairosvg/surface.py", line 469, in draw
    self.draw(child)
  File "/usr/local/lib/python3.6/dist-packages/cairosvg/surface.py", line 401, in draw
    TAGS[node.tag](self, node)
  File "/usr/local/lib/python3.6/dist-packages/cairosvg/image.py", line 28, in image
    image_bytes = node.fetch_url(url, 'image/*')
  File "/usr/local/lib/python3.6/dist-packages/cairosvg/parser.py", line 243, in fetch_url
    return read_url(url, self.url_fetcher, resource_type)
  File "/usr/local/lib/python3.6/dist-packages/cairosvg/url.py", line 143, in read_url
    return url_fetcher(url, resource_type)
  File "/usr/local/lib/python3.6/dist-packages/cairosvg/url.py", line 84, in fetch
    return urlopen(Request(url, headers=HTTP_HEADERS)).read()
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1459, in file_open
    return self.open_local_file(req)
  File "/usr/lib/python3.6/urllib/request.py", line 1498, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: '/bbb_rec/rec/presentation/6aa8ceb30c01be66d7b7474c29c9688c65e66c2b-1620204828346/poll_result16.svg'>

**Comment by C0D3D3V** [comment]
Oh, interesting I never have seen a bbb session with a poll, I will have a look into it.

**Comment by C0D3D3V** [comment]
By the way, if you are converting so many sessions to videos you should definitely check out the encoder option (https://github.com/C0D3D3V/bbb-dl/pull/6#issuecomment-791746636) if you have one (or more) graphics card(s) rendering will be much faster.

See https://trac.ffmpeg.org/wiki/HWAccelIntro#CUDANVENCNVDEC

**Comment by C0D3D3V** [comment]
I have found the problem and have already fixed it. I'm just testing if it works by downloading your given link, just takes a while as my computer is very slow. As soon as I have tested it successfully I will release the new version.

**Comment by C0D3D3V** [comment]
I released the new version. You can update by running: `pip install -U bbb-dl`

**Comment by C0D3D3V** [comment]
did it work?

**Comment by persuader** [comment]
Yes sir. Thanks and sorry for the late response i was away from pc.
