### ISSUE TITLE
Output folder

### ISSUE THREAD

**Issue by NiTRoeSE** [C0D3D3V/bbb-dl#16]
Hi,

is there any chance to implement  an "output folder" argument so that's its possible to output converted files to a defined path ?
Thanks in advanced.

**Comment by C0D3D3V** [comment]
Yes is possible, but actually unnecessary. If you like you can create a pullrequest. You just have to add a new program argument, e.g. `outputdir`. And pass this to the BBBDL, first you check if this is set, if yes the folder will be created if necessary and then the current working directory will be moved to this folder.

If you don't want to create a pull request, I can do that in the next few days as well.

**Comment by C0D3D3V** [comment]
Implemented in 0.9.8.2
to update run: `pip install --user -U bbb-dl`
