### ISSUE TITLE
Record Audio

### ISSUE THREAD

**Issue by Stilmant** [C0D3D3V/bbb-dl#22]
Hello, Not really an issue
I would like to thank you for this tool. Helped me a lot today.

What nice options could be to 
- a download mode only of all files. (a --backup option? )
- a option to generate audio file only (mp3/mp4) of the presentation 

Thanks again.

**Comment by C0D3D3V** [comment]
> a download mode only of all files. (a --backup option? )

You mean download only files from the server and do not generate any file? Sounds good, I could also make it so that if you used the backup option, you can later just run bbb-dl on the backup files.

> a option to generate audio file only (mp3/mp4) of the presentation

sounds simple, I can add it.

**Comment by C0D3D3V** [comment]
I added the backup option...

**Comment by C0D3D3V** [comment]
Added --audio-only in 1.0.0 feel free to test it

**Comment by Stilmant** [comment]
Hello, just this to thanks again for the feature. working flawless. a marvel :-D
