### ISSUE TITLE
webcam of the speaker not shown in the downloaded file

### ISSUE THREAD

**Issue by rdravi110** [C0D3D3V/bbb-dl#23]
Hi,

I downloaded a video recorded by bigbluebutton using bbb-dl and the final download did not contain the speaker's face/webcam. 

The original recording is here https://bbb2.gnome.org/playback/presentation/2.3/fc1100256b5e654028c835e803c284fefe572964-1670401621788, while the bbb-dl downloaded version is here https://up.nixnet.services/6u72ysuv.mp4.

**Comment by C0D3D3V** [comment]
Have you tried using the ` --add-webcam ` option?

**Comment by rdravi110** [comment]
Thanks. `--add-webcam` option worked fine.
