### ISSUE TITLE
Windows: Error operand type abs_outputdir

### ISSUE THREAD

**Issue by Einhuman197** [C0D3D3V/bbb-dl#27]
Latest Dependencies installed

There seems to be a problem with Windows Path handling

> [BBB] Trimming slide (frame 750 / 751) at time stamp 01:06:38 (Duration: 00:00:14)
[BBB] Trimming slide (frame 751 / 751) at time stamp 01:06:52 (Duration: 01:07:45)
[BBB] Concat Slideshow
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Tobs\AppData\Roaming\Python\Python311\Scripts\bbb-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\Tobs\AppData\Roaming\Python\Python311\site-packages\bbb_dl\main.py", line 1195, in main
    ).run(
      ^^^^
  File "C:\Users\Tobs\AppData\Roaming\Python\Python311\site-packages\bbb_dl\main.py", line 448, in run
    Path(abs_outputdir) / formatted_date + '_' + title.replace('/', '_', title.count('/')) + '.mp4'
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'WindowsPath' and 'str'

**Comment by Einhuman197** [comment]
Read the open issues, newest version is flawed, dev is working on it. Thanks for your hard work!

**Comment by C0D3D3V** [comment]
I'm working on a [rework](https://github.com/C0D3D3V/bbb-dl/tree/rework) , because there exists more than this error. But I will fix this error "quickly", hoping it work at least a little bit.

**Comment by C0D3D3V** [comment]
If the new release that I just made, is not working, than try to use version [v0.9.6](https://github.com/C0D3D3V/bbb-dl/releases/tag/v0.9.6) for now  (`pip uninstall bbb-dl` and `pip install bbb-dl==0.9.6.`), till I release the reworked version.

**Comment by C0D3D3V** [comment]
Please test the new release v9.9.9.0, if the error persists, please open a new issue
