### ISSUE TITLE
Ability to download multiple urls sequentially

### ISSUE THREAD

**Issue by Qbreak** [C0D3D3V/bbb-dl#30]
yes i need something like this :D

**Comment by C0D3D3V** [comment]
Do you need to be able to set filenames per URL, or is the video title good enough?

**Comment by Qbreak** [comment]
I did not understand

**Comment by C0D3D3V** [comment]
... does not matter maybe I will add a short script for it. 
But it is basically very easy to script this...

**Comment by Qbreak** [comment]
thank you I am waiting. In addition, when I add the h264_nvenc command, I get an error from ffmeg. This is not very important to me, but I can send the details if you want.

**Comment by C0D3D3V** [comment]
Sure send it to me if you have a verbose log.. I can not test the encoder functionality because I have a potato as computer.

**Comment by Qbreak** [comment]
I can send it within a day. open a new issue. I will send

**Comment by C0D3D3V** [comment]
Please test the new release. I added the command `bbb-dl-batch`. Very primitive batch processing. But maybe someone wants to make it better someday...

**Comment by C0D3D3V** [comment]
Try 0.9.9.4

**Comment by Qbreak** [comment]
okey

**Comment by Qbreak** [comment]
SIR

```
G:\bbb2\bbb-dl-0.9.9.4>bbb-dl-batch -fw 1280 -fh 720 --encoder h264_nvenc -bp G:\bbb2\bbb-dl-0.9.9.4\url_list.txt
usage: bbb-dl-batch [-h] [-bp BBB_DL_PATH] [-sw] [-swfd] [-sa] [-sc] [-bk] [-kt] [-v] [--ffmpeg-location FFMPEG_LOCATION] [-ncc] [--version] [--encoder ENCODER]
                    [--audiocodec AUDIOCODEC] [-od OUTPUT_DIR] [-wd WORKING_DIR] [-mpc MAX_PARALLEL_CHROMES] [-fw FORCE_WIDTH] [-fh FORCE_HEIGHT]
                    URLs
bbb-dl-batch: error: the following arguments are required: URLs

G:\bbb2\bbb-dl-0.9.9.4>bbb-dl-batch -fw 1280 -fh 720 --encoder h264_nvenc -bp G:\bbb2\bbb-dl-0.9.9.4
usage: bbb-dl-batch [-h] [-bp BBB_DL_PATH] [-sw] [-swfd] [-sa] [-sc] [-bk] [-kt] [-v] [--ffmpeg-location FFMPEG_LOCATION] [-ncc] [--version] [--encoder ENCODER]
                    [--audiocodec AUDIOCODEC] [-od OUTPUT_DIR] [-wd WORKING_DIR] [-mpc MAX_PARALLEL_CHROMES] [-fw FORCE_WIDTH] [-fh FORCE_HEIGHT]
                    URLs 
```

**Comment by C0D3D3V** [comment]
You have to run it with a file containing BBB URLs like this: `bbb-dl-batch my_session_urls.txt`  or `bbb-dl-batch path/to/my_session_urls.txt`

**Comment by C0D3D3V** [comment]
Just leave out the `-bp`

**Comment by Qbreak** [comment]
what will be the arguments

**Comment by C0D3D3V** [comment]
`bbb-dl-batch -fw 1280 -fh 720 --encoder h264_nvenc G:\bbb2\bbb-dl-0.9.9.4\url_list.txt`

**Comment by Qbreak** [comment]
:D

**Comment by Qbreak** [comment]
I am trying

**Comment by Qbreak** [comment]
There is silence on my CLI screen, should I inform the bomb disposal team :D

**Comment by C0D3D3V** [comment]
I have not tested it on windows... could be that it does not work on windows. I can test it tomorrow.

**Comment by C0D3D3V** [comment]
Ok, tested it, yes windows bugs again... I have to change the subproces call...
