### ISSUE TITLE
Error h264

### ISSUE THREAD

**Issue by Qbreak** [C0D3D3V/bbb-dl#31]
[debug_264.zip](https://github.com/C0D3D3V/bbb-dl/files/10367979/debug_264.zip)

**Comment by C0D3D3V** [comment]
Try version 9.9.9.3, I think this should fix it. I'm also no ffmpeg expert, so I'm not sure if my chosen options are good ... but at least they work :D

**Comment by Qbreak** [comment]
```
PS G:\bbb2\bbb-dl-9.9.9.3> bbb-dl-batch --help
bbb-dl-batch : The term 'bbb-dl-batch' is not recognized as the name of a cmdlet, function, script file, or operable pr
ogram. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ bbb-dl-batch --help
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bbb-dl-batch:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: The command bbb-dl-batch was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\bbb-dl-batch". See "get-help about_Command_Precedence" for more details.
```

**Comment by Qbreak** [comment]
```
PS G:\bbb2\bbb-dl-9.9.9.3> bbb-dl --verison
usage: bbb-dl [-h] [-sw] [-swfd] [-sa] [-sc] [-bk] [-kt] [-v] [--ffmpeg-location FFMPEG_LOCATION] [-ncc] [--version]
              [--encoder ENCODER] [--audiocodec AUDIOCODEC] [-f FILENAME] [-od OUTPUT_DIR] [-wd WORKING_DIR]
              [-mpc MAX_PARALLEL_CHROMES] [-fw FORCE_WIDTH] [-fh FORCE_HEIGHT]
              URL
bbb-dl: error: the following arguments are required: URL
```

version error?

**Comment by Qbreak** [comment]
```
PS G:\bbb2\bbb-dl-9.9.9.3> bbb-dl --version
bbb-dl 0.9.9.3
```

**Comment by Qbreak** [comment]
thanks :D 

How do we use ffmpeg -fast -very-fast arguments? Also, while you have found you active, can you activate ffmpeg if there are any presets that will enable it to process in higher quality :D

**Comment by C0D3D3V** [comment]
It does not really make sense to use presets with higher quality, because it is only a slideshow... We have no quick movements, no color shifts... nothing special. The result from preset fast to slow is nearly the same, it only takes more time to process.   But if you want I can add a option to set the preset by option.

See also https://write.corbpie.com/ffmpeg-preset-comparison-x264-2019-encode-speed-and-file-size/ and other comparisons you can find online..

**Comment by C0D3D3V** [comment]
What really would make a difference, is if someone would take on this project and change the frame capture algorithm so that the screenshots are not taken in viewbox size, but in the size of wanted output resolution. That would make the output a lot lot better.

**Comment by C0D3D3V** [comment]
> I can add a option to set the preset by option.

Make a new issue if you want that

**Comment by C0D3D3V** [comment]
I added the --preset option in v0.9.9.5
