### ISSUE TITLE
Change the frame capture algorithm so that the screenshots are not taken in viewbox size, but in the size of wanted output resolution

### ISSUE THREAD

**Issue by C0D3D3V** [C0D3D3V/bbb-dl#32]
Add pad already in chrome browser.

**Comment by Qbreak** [comment]
dude, you are the professional in this business. The only reason I'm stuck with it
  It would be nice if we could add the settings that will make the text a little clearer because of the eyestrain caused by the blurry texts. According to what she said, it is necessary to write an algorithm. ok, let me try it like this, it's enough in its current state :D

**Comment by C0D3D3V** [comment]
Its more a puzzle then a algorithm xD But you can figure it out in a day of work... But I currently do not want to solve this puzzle, I have other things to do. Maybe in a few days. 

But as I already told you, you can use the backup option, and as soon as the algorithm is better, you can generate the videos in better quality.

**Comment by Qbreak** [comment]
By the way, the program is active. there is no error. but I guess he doesn't want to give information about what he does :D

**Comment by C0D3D3V** [comment]
For now you can also just not use --force-width and --force-height. Because then ffmpeg does not need to shrink the images. But I have already an idea how I will solve the problem.

**Comment by C0D3D3V** [comment]
I have made the changes in v0.9.9.7. Do not expect the quallity to be much better... since the result can not be better than in the original session that you can watch in the browser. Also the base images have only a limited resolution e.g. in the presentation you send me 1131x1600 so every rendering with width bigger than 1131 will be scaled with not sharp letters.  Also sometimes in that presentation is zoomed in to 646 px width so that this is always scaled. 

I could add an option to not zoom at all, that would make the output more sharp.

**Comment by Qbreak** [comment]
As far as I understand, you have made corrections to make the images sharper, and the option to change the frame height is disabled for now in the last version you released. my english is bad :D.

**Comment by C0D3D3V** [comment]
No it is not disabled, you can use all options.

But I just noticed an error in my latest release. Do not use v0.9.9.7 yet... I will make a fix.

**Comment by Qbreak** [comment]
haaa okey.ben I was sad for the 6-hour process I started. thanks

**Comment by C0D3D3V** [comment]
the bug in 0.9.9.7 is fixed in 0.9.9.8 but it was not really a big bug, if you made progress with it, the videos should be finde. But I think you used 0.9.9.6, there was all fine
