### ISSUE TITLE
bbb-dl-barch process info does not appear and it doesn't work properly

### ISSUE THREAD

**Issue by Qbreak** [C0D3D3V/bbb-dl#33]
By the way, the program is active. there is no error. but I guess he doesn't want to give information about what he does :D
![Ekran görüntüsü 2023-01-09 042409](https://user-images.githubusercontent.com/33759541/211228772-af014e65-440f-4124-a21f-33620ec2b4bd.png)

**Comment by Qbreak** [comment]
i think he is sleeping
![654654654](https://user-images.githubusercontent.com/33759541/211232488-ab0ed05f-4f52-4714-a2b3-552498bb7bef.png)

**Comment by Qbreak** [comment]
the program could not download more than one url, it gets stuck

**Comment by Qbreak** [comment]
I can send the output file if you want.

**Comment by Qbreak** [comment]
ffmpeg doesn't create any files after consuming 1GB ram for 1 hour

**Comment by C0D3D3V** [comment]
Windows ist pretty dumb... I will make a fix...

**Comment by C0D3D3V** [comment]
try v0.9.9.6

**Comment by Qbreak** [comment]
ahh yes, here are 10 videos ready immediately :D perfect. I didn't get any error but if i do i will post
