### ISSUE TITLE
TypeError: 'ABCMeta' object is not subscriptable

### ISSUE THREAD

**Issue by zoranmarkovic2001** [C0D3D3V/bbb-dl#40]
_Ubuntu Mate 20.04.6 LTS
Python 3.8.10  
ffmpeg version 4.2.7_

I followed the instructions:
>pip install --user bbb-dl
>playwright install chromium
>bbb-dl

```
Traceback (most recent call last):
  File "/home/user/.local/bin/bbb-dl", line 5, in <module>
    from bbb_dl.main import main
  File "/home/user/.local/lib/python3.8/site-packages/bbb_dl/main.py", line 32, in <module>
    from bbb_dl.ffmpeg import FFMPEG
  File "/home/user/.local/lib/python3.8/site-packages/bbb_dl/ffmpeg.py", line 10, in <module>
    from ffmpeg.asyncio import FFmpeg
  File "/home/user/.local/lib/python3.8/site-packages/ffmpeg/asyncio/__init__.py", line 1, in <module>
    from .ffmpeg import FFmpeg
  File "/home/user/.local/lib/python3.8/site-packages/ffmpeg/asyncio/ffmpeg.py", line 14, in <module>
    from ffmpeg.asyncio.utils import create_subprocess, ensure_stream_reader, read_stream, readlines
  File "/home/user/.local/lib/python3.8/site-packages/ffmpeg/asyncio/utils.py", line 12, in <module>
    def create_subprocess(*args: Any, **kwargs: Any) -> Awaitable[asyncio.subprocess.Process]:
TypeError: 'ABCMeta' object is not subscriptable
```

a few months ago I used bbb-dl on mate and everything worked fine

**Comment by C0D3D3V** [comment]
Please make again sure you are on latest version:
`pip install --user -U  bbb-dl`

tell me then the version of bbb-dl using the --version option

**Comment by zoranmarkovic2001** [comment]
I tested bbb-dl on classic Ubuntu 22.04 it works fine, it seems to be a problem with Ubuntu Mate OS, python return same error on start bbb-dl

**Comment by C0D3D3V** [comment]
I guess it is a problem with python 8. What is the python version on your other system?

**Comment by zoranmarkovic2001** [comment]
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux

**Comment by C0D3D3V** [comment]
If the maintainer of python-ffmpeg does not fix it before me, I can make a PR later this week on the project I refered above...

**Comment by zoranmarkovic2001** [comment]
It's not urgent for me, I thought it was a bbb-dl error, apparently the problem is in python 3.8 on 3.10 it works great
sorry for my bad english

**Comment by C0D3D3V** [comment]
should be fixed now. You just have to update again or update python-ffmpeg

**Comment by zoranmarkovic2001** [comment]
now work fine
