### ISSUE TITLE
How to run the tool (for dummies).

### ISSUE THREAD

**Issue by ntpgygms** [C0D3D3V/bbb-dl#43]
Hi! I hope you are doing fine. 
First, thanks for sharing this project :)

On the other hand, can you provide further guidance on how to run the tool, please? I know the readme file lists the steps from installing to running, but when following it, either on CMD or Powershell, I get this error: 
```
bbb-dl : The term 'bbb-dl' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
```
This might be a silly error, but being a newbie, I am not quite sure how to overcome it. 
Thanks in advance for your time and advice.

**Comment by C0D3D3V** [comment]
What did `pip install --user bbb-dl` print?

**Comment by C0D3D3V** [comment]
> First, thanks for sharing this project :)

You are welcome :) Actually I did this project only for you 🤗 And I hope it will help you. I'm not using it myself, and never did. But I thought this can help students and other people a lot.

**Comment by ntpgygms** [comment]
> What did `pip install --user bbb-dl` print?

Hi! Thanks for your prompt response. 
This is the actual output: 

![image](https://user-images.githubusercontent.com/90012422/236632664-c290d2c9-3137-46df-b28b-b5c71c2a4141.png)
 After that, and when trying to run the `bbb-dl` command, got the error a reported on my initial post.
 
 Any advice or recommendation, is highly appreciated.

**Comment by C0D3D3V** [comment]
Is Administrator also the user you used to run `bbb-dl`?
With the `--user` option you installed bbb-dl only for the Administrator user

**Comment by ntpgygms** [comment]
> Is Administrator also the user you used to run `bbb-dl`? With the `--user` option you installed bbb-dl only for the Administrator user

Yes, it was. And no matter if it is the Windows Terminal, CMD, or PowerShell (all ran as Admin), I get the same error: 

```
C:\Users\Administrator>bbb-dl --help
'bbb-dl' is not recognized as an internal or external command,
operable program or batch file.
```
```
PS C:\Users\Administrator> bbb-dl --help
bbb-dl : The term 'bbb-dl' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ bbb-dl --help
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (bbb-dl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by C0D3D3V** [comment]
Very interesting.  Try installing it without the `--user` flag.

Just a workaround: In your screenshot above, you see the full path of bbb-dl, you could run the full path instead of the short command, but that is very ugly.

**Comment by ntpgygms** [comment]
Tried without the `--user` flag. 
Then, tried to run the `bbb-dl` command. Same result. 

Tried running with the complete path. Same error: 
![image](https://user-images.githubusercontent.com/90012422/236646134-d04c9673-cc33-4c26-a15a-4eaceb114fa6.png)

For the record, the `ffmpeg` has been added to the PATH. Still, the issue persists.

**Comment by ntpgygms** [comment]
> Tried without the `--user` flag. Then, tried to run the `bbb-dl` command. Same result.
> 
> Tried running with the complete path. Same error: ![image](https://user-images.githubusercontent.com/90012422/236646134-d04c9673-cc33-4c26-a15a-4eaceb114fa6.png)
> 
> For the record, the `ffmpeg` has been added to the PATH. Still, the issue persists.

Good news! Just after I sent the reply above, I realized I was under the wrong directory. Moved back to the `scripts` one and the commands returned the expected result (yay!).
I am running a test with a BBB recording and, so far: 
![image](https://user-images.githubusercontent.com/90012422/236646504-8467b90c-d750-49b8-b050-dbe1e4693b73.png)

Will keep you posted.

**Comment by C0D3D3V** [comment]
You can add now the Path you used now to run bbb-dl, to your System PATH variable, like you did for ffmpeg. 
It should be easy to find some tutorial how to add a path to your system PATH  setting. 

After you did that, you should be able to run bbb-dl just using its command.

**Comment by ntpgygms** [comment]
Thanks! Just had the complete path added, did a reboot, and voilá!
Appreciate your efforts and support. So far, I've been able to download some of my class recordings. Will mark this thread as closed. 

Have a nice day!

**Comment by REVELLIOM** [comment]
> > Tried without the `--user` flag. Then, tried to run the `bbb-dl` command. Same result.
> > Tried running with the complete path. Same error: ![image](https://user-images.githubusercontent.com/90012422/236646134-d04c9673-cc33-4c26-a15a-4eaceb114fa6.png)
> > For the record, the `ffmpeg` has been added to the PATH. Still, the issue persists.
> 
> Good news! Just after I sent the reply above, I realized I was under the wrong directory. Moved back to the `scripts` one and the commands returned the expected result (yay!). I am running a test with a BBB recording and, so far: ![image](https://user-images.githubusercontent.com/90012422/236646504-8467b90c-d750-49b8-b050-dbe1e4693b73.png)
> 
> Will keep you posted.

**What path did you use to run bbb-dl?**
