### ISSUE TITLE
Downloaded Video has no sound

### ISSUE THREAD

**Issue by Cla33ic** [C0D3D3V/bbb-dl#44]
Thank you for your work on this project! I attempted to download a video, and after completion, I realized there is no audio. Could you possibly assist me with this issue? Thank you

**Comment by testobserver** [comment]
usual windows apps play it without sound, try VLC or just upload to Youtube

**Comment by C0D3D3V** [comment]
Would be great if someone shares a lecture where this happens. And even better if someone plays with the ffmpeg commands to create an output that is playable under windows.

**Comment by C0D3D3V** [comment]
Try to open the Video with VLC player or mpv player

**Comment by andrejpejovski** [comment]
I found out that audio of the downloaded file is M4A which is not supported in apps like Adobe Premiere Pro, so is it possible with this command `--audiocodec AUDIOCODEC` to set the audio in the right codec? And if yes how to do it?

**Comment by C0D3D3V** [comment]
Try `--audiocodec mp3`. The proof of the pudding is in the eating.

**Comment by C0D3D3V** [comment]
See https://trac.ffmpeg.org/wiki/Encode/HighQualityAudio for supported codecs

**Comment by C0D3D3V** [comment]
So I guess using `--audiocodec mp3` should fix fhe problem.
