### ISSUE TITLE
Zero Division Error

### ISSUE THREAD

**Issue by krim404** [C0D3D3V/bbb-dl#46]
When i try to render some videos, a few are failed with the following message:

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/bbb_dl/main.py", line 434, in _real_multi_capture_frames
    await gather_jobs
  File "/opt/homebrew/lib/python3.11/site-packages/bbb_dl/main.py", line 555, in capture_frames
    await self.set_view_box(page, action)
  File "/opt/homebrew/lib/python3.11/site-packages/bbb_dl/main.py", line 620, in set_view_box
    aspect_ratio = action.width / action.height
                   ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero
Unexpected Error! Press Ctr+C to exit. Please try to set a low number of threads with `--max-parallel-chromes`. You can contact bbb-dl support.
```

sadly i cannot provide the source data, as they are confidential - but i can assist with information

**Comment by testobserver** [comment]
It worked on the most part of my lectures but stopped to work and gave this error when Prof. shared not only horizontal PP slide but some vertical page from pdf, so , I guess, it is unable to get constant height and width throughout a lecture.

**Comment by C0D3D3V** [comment]
I mean, treating the symptom would be very easy. And someone could just avoid the division by 0 and do a PR. But this is just the symptom, if someone has a lecture where the error happens, it would be great if you share it here.

**Comment by testobserver** [comment]
@C0D3D3V If you want I can send to your email, I just don't want to publicly share the link there

**Comment by C0D3D3V** [comment]
Send it over, I can test it in my free time...

**Comment by testobserver** [comment]
Thanks

**Comment by C0D3D3V** [comment]
Please test version 1.0.7
