### ISSUE TITLE
bbb-dl install fails

### ISSUE THREAD

**Issue by ricardo-bigdata** [C0D3D3V/bbb-dl#48]
Hi.

I have Ubuntu 18, python 3.8.10, and I've installed ffmpeg. When I try install bbb-dl, it doesn't work and get next error:

**ERROR: Could not find a version that satisfies the requirement PySide6>=6.5.0 (from bbb-dl) (from versions: 6.0.0a1.dev1606911628, 6.0.0, 6.0.1, 6.0.2, 6.0.3, 6.0.4, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.2.0, 6.2.1, 6.2.2, 6.2.2.1, 6.2.3, 6.2.4)
ERROR: No matching distribution found for PySide6>=6.5.0 (from bbb-dl)**

Is there any solution?

**Comment by C0D3D3V** [comment]
looks more like the output of python 3.6
Try to install Pyside6 seperatly

**Comment by C0D3D3V** [comment]
Since the feature for that I use PySide6 does not even work (and none of the people that wanted it, wants to help). I guess I will remove the dependency today.

**Comment by C0D3D3V** [comment]
Please try v1.0.6. Open a new issue if you still have problems.
