### ISSUE TITLE
AV1 Codec problem

### ISSUE THREAD

**Issue by qpeyba** [C0D3D3V/bbb-dl#49]
for some reason av1 encoder makes some recordings with no picture, just white screen with sound, how can this be fixed?

**Comment by qpeyba** [comment]
h265 codec also works the same way

**Comment by qpeyba** [comment]
accidentally closed

**Comment by C0D3D3V** [comment]
you could play around with the ffmpeg commands and find better parameters, that produces in that cases a valid file.

**Comment by C0D3D3V** [comment]
maybe you can als ask in some forum if some ffmpeg expert has an idea

**Comment by qpeyba** [comment]
Okay, anyway thanks for this uploader, it helps a lot

**Comment by C0D3D3V** [comment]
I guess if no one is willing to invest some time in this problem :D It will stay like this....
