### ISSUE TITLE
ffmpeg error

### ISSUE THREAD

**Issue by federicotorrielli** [C0D3D3V/bbb-dl#5]
![error_bbbdl](https://user-images.githubusercontent.com/31370059/110165288-04716f80-7df3-11eb-9b23-8acbbfdc5e50.png)

- Command: bbb-dl *link* -aw -aa
- Link (so you can test it too): https://bbb-cluster.di.unito.it/playback/presentation/2.0/playback.html?meetingId=aa2f077516155b42a07af3eb8441647d8d84e204-1614850999725

I will look into this tomorrow myself, just posting the image of the error, seems related to ffmpeg.

> I am also implementing an option to use nvenc to encode for ffmpeg.

**Comment by federicotorrielli** [comment]
Pull request #6 fixes this issue, waiting for merge.

**Comment by C0D3D3V** [comment]
Should be fixed right?
