### ISSUE TITLE
White screen display during playback

### ISSUE THREAD

**Issue by 8zizek8** [C0D3D3V/bbb-dl#50]
Hi @C0D3D3V
At different times of video. A white screen appears. They stay for a while and leave again. It seems that some content has not been converted

**Comment by C0D3D3V** [comment]
can you send me the URL to the bbb session and the parameters you used for bbb-dl?

**Comment by 8zizek8** [comment]
Here you are:
    python downloader.pyz SE01 
    https://conf2.anisa.co.ir/playback/presentation/2.3/aefeeb8e34eb48cdd846993a15051c80ca4593c1-1692879978011

**Comment by 8zizek8** [comment]
Here you are:
```shell
python downloader.pyz SE01 https://conf2.anisa.co.ir/playback/presentation/2.3/aefeeb8e34eb48cdd846993a15051c80ca4593c1-1692879978011
```

**Comment by 8zizek8** [comment]
Here you are:
```shell
bbb-dl -sw -f Se011 -fw 1920 -fh 1080 https://conf2.anisa.co.ir/playback/presentation/2.3/aefeeb8e34eb48cdd846993a15051c80ca4593c1-1692879978011
```

**Comment by 8zizek8** [comment]
Here you are:
```shell
bbb-dl -f Se011 https://conf2.anisa.co.ir/playback/presentation/2.3/aefeeb8e34eb48cdd846993a15051c80ca4593c1-1692879978011
```

**Comment by C0D3D3V** [comment]
Funny that bbb-dl can download the session, but to view it in the browser you need a login.

**Comment by 8zizek8** [comment]
Thank you for your reply.
Do you think there is a way to make your script work properly with this URL? Because the script is perfect and it works. The only problem is the occasional bleaching.

**Comment by C0D3D3V** [comment]
My computer already renders for like 2h, but probably needs two more hours. But you could already tell me time marks when the thing happens that you mean.

**Comment by 8zizek8** [comment]
Thank you for your reply.
Honestly, I think this happens randomly, that is, at different times and randomly, but let me take a new output and tell you.

**Comment by 8zizek8** [comment]
Again, I got the output with these parameters:
```shell
bbb-dl -sw -swfd -f Se01 https://conf2.anisa.co.ir/playback/presentation/2.3/aefeeb8e34eb48cdd846993a15051c80ca4593c1-1692879978011
``` 
It was even more white. It seems to me that it turns white where deskshare is being displayed.

**Comment by C0D3D3V** [comment]
Yes I see. My computer is not yet finished with the rendering but it already shows a lot of white in presentation.mp4 when it should actually display the deskshare.

**Comment by C0D3D3V** [comment]
I can investigate what is going wrong

**Comment by C0D3D3V** [comment]
Please test v1.0.8 I'm not very happy with the fix. But I have to learn more about video containers to fix it in a better way, so that the rendering is faster.

**Comment by 8zizek8** [comment]
Thank you, the script is excellent, I will test it.
