### ISSUE TITLE
Deskshare is downloaded but it's not included in the final video

### ISSUE THREAD

**Issue by andrejpejovski** [C0D3D3V/bbb-dl#55]
**What is the problem?**
The problem is that the deskshare video is downloaded but its not included in the final mp4 video.

**What i think is the problem & more details about it?**
My professor is sharing vertical pdf file (resolution (1280px x 1600px)) where the the exercises are and after every exercise she's switching to screen sharing (idk the resolution of the deskshare video) her monitor which is horizontal resolution.

And i think the problem is something with the orientation of both **deskshare** and **frames slideshow** generated video.

In the cmd i don't get any errors or warnings everything works fine but at the end the final video is just the frames slideshow and when it comes to the professor sharing her screen the final video is white screen while audio is playing just fine.

The final video is vertical (1280px x 1600px)

**I also have uploaded the final video file (WeTransfer)**
👉 https://we.tl/t-8CJOLJU3Kh

**Here is a list of urls of BBB sessions where this problem occur.**
[https://bbb-lb.finki.ukim.mk/playback/presentation/2.3/e687769c24cfe30c6bfbd7c7555457327a6c7f65-1653292331494](url)
[https://bbb-lb.finki.ukim.mk/playback/presentation/2.3/e687769c24cfe30c6bfbd7c7555457327a6c7f65-1652694108575](url)
[https://bbb-lb.finki.ukim.mk/playback/presentation/2.3/e687769c24cfe30c6bfbd7c7555457327a6c7f65-1652689827442](url)
[https://bbb-lb.finki.ukim.mk/playback/presentation/2.3/e687769c24cfe30c6bfbd7c7555457327a6c7f65-1652085694446](url)
[https://bbb-lb.finki.ukim.mk/playback/presentation/2.3/e687769c24cfe30c6bfbd7c7555457327a6c7f65-1650352496283](url)
[https://bbb-lb.finki.ukim.mk/playback/presentation/2.3/e687769c24cfe30c6bfbd7c7555457327a6c7f65-1650271681975](url)
[https://bbb-lb.finki.ukim.mk/playback/presentation/2.3/e687769c24cfe30c6bfbd7c7555457327a6c7f65-1647856051948](url)
[https://bbb-lb.finki.ukim.mk/playback/presentation/2.3/e687769c24cfe30c6bfbd7c7555457327a6c7f65-1647251849520](url)
[https://bbb-lb.finki.ukim.mk/playback/presentation/2.3/e687769c24cfe30c6bfbd7c7555457327a6c7f65-1646645958426](url)
[https://bbb-lb.finki.ukim.mk/playback/presentation/2.3/e687769c24cfe30c6bfbd7c7555457327a6c7f65-1646036183863](url)
[https://bbb-lb.finki.ukim.mk/playback/presentation/2.3/e687769c24cfe30c6bfbd7c7555457327a6c7f65-1645436560506](url)
[https://bbb-lb.finki.ukim.mk/playback/presentation/2.3/323650a7a525a8ff5ff457fb6afbeffc2a25e1cd-1621414425638?meetingId=323650a7a525a8ff5ff457fb6afbeffc2a25e1cd-1621414425638](url)

**I zipped the temporary files folder and here is a wetransfer link for it just in case you want to see it (7zip)**
👉 https://we.tl/t-Ez8SkUrnXd

**Here is my full CMD log file with `--verbose` command running**
[CMD Log.txt](https://github.com/C0D3D3V/bbb-dl/files/14996439/CMD.Log.txt)

**Comment by C0D3D3V** [comment]
Amazing how fast bbb-dl is for you :D On my bum PC it would take at least 1h, more like 2.
I will take a look at it.

**Comment by andrejpejovski** [comment]
I started using `--encoder hevc_nvenc` i have RTX3060 6GB laptop graphics card

**Comment by C0D3D3V** [comment]
The problem is, that deskshare.mp4 is in HEVC encoding (codec of your hevc_nvenc) and slideshow.mp4 is in h.264. FFMPEG concat can not concatenate different codecs. Thats why without hw-encoder it works (as it does on my computer). 
Its time we move away from concat to concat filter, there ffmpeg will transcode the codec of slideshow.mp4

**Comment by andrejpejovski** [comment]
So you want to say to me to stop using `--encoder hevc_nvenc`, right?

**Comment by C0D3D3V** [comment]
No, I want  to say, that I have to fix this in the code

**Comment by andrejpejovski** [comment]
Okay so you want to say that for now i cant do anything about these sessions to download properly and i need to wait new updates on the repo from you, right?

**Comment by C0D3D3V** [comment]
Before I make now big changes to the code. Please test if the new version solves the problem. https://github.com/C0D3D3V/bbb-dl/releases/tag/1.0.11
remove presentation.mp4 and slideshow.mp4 from your temporary files, and the final video.

**Comment by andrejpejovski** [comment]
Okay, i'll let you know in the next hour

**Comment by C0D3D3V** [comment]
* you could also just render with CPU Encoder, that should render in h.264
but that does not solve the problem for your gpu

**Comment by andrejpejovski** [comment]
Will it be faster if i render with CPU encoder?
And if it does how to do that?

**Comment by C0D3D3V** [comment]
See readme:


    For Intel CPUs, you can try the encoder h264_qsv (Use the option --encoder h264_qsv). Sometimes this encoder is faster than your graphics card encoder.

    For AMD CPUs / GPUs, you can try the encoder h264_amf (Use the option --encoder h264_amf).

With such a big GPU, your GPU is probably faster, but if you have a very good CPU it will be faster, because CPUs often have specialized h.264 encoders / decoders.

**Comment by andrejpejovski** [comment]
Okay thank you a lot, you're very helpfull.
I have AMD Ryzen 9 5900HX - and will try with the processor and tell you.

**Comment by andrejpejovski** [comment]
It still don't work for me. I deleted the temp files, got the newest commits of the repo and still deskshare video doesnt shows up on the final output video.

Here is my cmd log file:
[CMD Log2.txt](https://github.com/C0D3D3V/bbb-dl/files/14999640/CMD.Log2.txt)

Am i doing something wrong?

**Comment by C0D3D3V** [comment]
your log does not use the latest version. either use the file that is in the folder: run `.\bbb-dl` or install the update with `pip install -U bbb-dl` and then run `bbb-dl` normally.

**Comment by andrejpejovski** [comment]
How you were sure that i dont have newest version just from looking of my cmd log file.

However i checked this time and am sure that i have the latest version (v1.0.11)
👇 Screenshot from `git log`
![git log](https://github.com/C0D3D3V/bbb-dl/assets/128852423/41eeae04-5ecc-42ac-bed3-606f77cf214c)

👇CMD log file that i runned once more after i was sure that i have the latest version
[CMD Log3.txt](https://github.com/C0D3D3V/bbb-dl/files/15000565/CMD.Log3.txt)

**For me the problem is still not solved.**

**Comment by C0D3D3V** [comment]
I'm sure because the ffmpeg command is old and I changed something in the output of rendering frames. 

You are still on old version. Run `bbb-dl --version` to see your version.

**Comment by andrejpejovski** [comment]
Hmm yep. It says 1.0.9.

Am confused af right now. Why when i try git pull it says i am up to date.

**Comment by C0D3D3V** [comment]
you run bbb-dl that is installed on your system, not that, that is located in the git folder. If you want to run that, than type `path\to\git\folder\bbb-dl` or open cmd in that folder and run `pip install .`

**Comment by andrejpejovski** [comment]
I managed to get to the 1.011 version and now am experiencing some new errors.
[CMD4.txt](https://github.com/C0D3D3V/bbb-dl/files/15003457/CMD4.txt)

**Comment by andrejpejovski** [comment]
I got v1.0.11 and everything's fine. Thanks a lot 🙌

**Comment by C0D3D3V** [comment]
does it also work with mp3 audio codec?

**Comment by andrejpejovski** [comment]
Yes, it works with mp3 also.
