### ISSUE TITLE
metadata.xml & shapes.svg error

### ISSUE THREAD

**Issue by andrejpejovski** [C0D3D3V/bbb-dl#56]
I'am trying to donwload the following BBB Recording here is a link:
[https://bbb-lb.finki.ukim.mk/playback/presentation/2.3/8f2197b08b166f4ddb96d2bb32d32db393552b08-1634198893582?meetingId=8f2197b08b166f4ddb96d2bb32d32db393552b08-1634198893582](url)

It keeps failing.
![Screenshot 2024-07-13 211002](https://github.com/user-attachments/assets/ff32ff2c-3812-497a-bb50-c5ce6ced7abc)

**Comment by C0D3D3V** [comment]
Uae the option --skip-cert-verify

**Comment by andrejpejovski** [comment]
![Screenshot 2024-07-13 211920](https://github.com/user-attachments/assets/7c34c46a-b059-481e-9a3e-d56dc75af5af)

**Comment by C0D3D3V** [comment]
I added the option in latest version. Update with `pip install -U bbb-dl`
then try again.

**Comment by C0D3D3V** [comment]
In your version there is a similar option called -ncc that could work too.

**Comment by andrejpejovski** [comment]
> In your version there is a similar option called -ncc that could work too.

Thank you man. -ncc it works. Is the command going to work (including -ncc) when my college will renew their SSL sertificate?

**Comment by C0D3D3V** [comment]
Yes, if the certificates are fixed bbb-dl will work with -`ncc` too, but you will no longer need the option (its in therory a security problem, in practise you will have no issues).
