### ISSUE TITLE
Can't download deskshare mp4

### ISSUE THREAD

**Issue by EnesOz1** [C0D3D3V/bbb-dl#60]
```
external_videos.json could not be downloaded: 404 Not Found
Successfully downloaded slides_new.xml
video/webcams.webm could not be downloaded: 404 Not Found
polls.json could not be downloaded: 404 Not Found
deskshare/deskshare.mp4 could not be downloaded: 404 Not Found
video/webcams.mp4 got 10.00KiB / 138.19MiB
deskshare/deskshare.webm could not be downloaded: 404 Not Found
```

In terminal i got those error. It downloads webcam video, take every frame but i can't download the video record.

**Comment by C0D3D3V** [comment]
About what video recording are you speaking? If it does not download the deskshare, there was probably no desk shared in the session. Else you would later get a real error.

**Comment by EnesOz1** [comment]
> About what video recording are you speaking? If it does not download the deskshare, there was probably no desk shared in the session.

I want to download a presentation like the attached photos.

![resim_2024-10-25_223509707](https://github.com/user-attachments/assets/68c6a031-5f8a-461f-aca9-37c6efc0ffdd)

**Comment by C0D3D3V** [comment]
Does not look like deskshare for me. Just normal slides

**Comment by C0D3D3V** [comment]
If you want to create a video from the session. Just let bbb-dl run till it is complete.

**Comment by EnesOz1** [comment]
> If you want to create a video from the session. Just let bbb-dl run till it is complete.

Yes i want the video but i can't understand how should i do.

**Comment by C0D3D3V** [comment]
What is the problem? Send the complete terminal output.

**Comment by C0D3D3V** [comment]
Is something missing in the final video?

**Comment by EnesOz1** [comment]
The problem it says no deskshare found. It's captures every frame. But i want the video and audio. Because in presentation it seems like video. 

```
(venv) C:\Users\eneso\Desktop\videolar>bbb-dl -sc https://canliders.kemalhoca.com/playback/presentation/2.3/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119
Output directory for the final video is: C:\Users\eneso\Desktop\videolar
Directory for the temporary files is: C:\Users\eneso\AppData\Local\bbb-dl\7a6c36684e75ca32a09f13155137294b
Downloading meta information
Downloading metadata.xml...
Downloading shapes.svg...
shapes.svg got 10.00KiB / 1.58MiB
metadata.xml got 2.54KiB / 2.54KiB
Successfully downloaded metadata.xml
shapes.svg got 863.76KiB / 1.58MiB
Successfully downloaded shapes.svg
Downloading webcams / deskshare
Downloading cursor.xml...
Downloading panzooms.xml...
Downloading captions.json...
Downloading deskshare.xml...
Downloading events.xml...
Downloading presentation_text.json...
Downloading slides_new.xml...
Downloading notes.html...
Downloading polls.json...
Downloading external_videos.json...
Downloading video/webcams.webm...
Downloading video/webcams.mp4...
Downloading deskshare/deskshare.webm...
Downloading deskshare/deskshare.mp4...
panzooms.xml got 10.00KiB / 16.81KiB
Successfully downloaded panzooms.xml
captions.json got 2.00B / 2.00B
Successfully downloaded captions.json
events.xml could not be downloaded: 404 Not Found
cursor.xml got 10.00KiB / 562.80KiB
deskshare.xml got 86.00B / 86.00B
Successfully downloaded deskshare.xml
presentation_text.json got 9.48KiB / 9.48KiB
Successfully downloaded presentation_text.json
notes.html could not be downloaded: 404 Not Found
slides_new.xml got 10.00KiB / 31.93KiB
polls.json could not be downloaded: 404 Not Found
Successfully downloaded slides_new.xml
Successfully downloaded cursor.xml
external_videos.json could not be downloaded: 404 Not Found
video/webcams.mp4 got 10.00KiB / 117.32MiB
video/webcams.webm could not be downloaded: 404 Not Found
deskshare/deskshare.webm could not be downloaded: 404 Not Found
deskshare/deskshare.mp4 could not be downloaded: 404 Not Found
video/webcams.mp4 got 809.76KiB / 117.32MiB
video/webcams.mp4 got 1.57MiB / 117.32MiB
video/webcams.mp4 got 2.40MiB / 117.32MiB
video/webcams.mp4 got 3.18MiB / 117.32MiB
video/webcams.mp4 got 3.96MiB / 117.32MiB
video/webcams.mp4 got 4.76MiB / 117.32MiB
video/webcams.mp4 got 5.56MiB / 117.32MiB
video/webcams.mp4 got 6.34MiB / 117.32MiB
video/webcams.mp4 got 7.13MiB / 117.32MiB
video/webcams.mp4 got 7.92MiB / 117.32MiB
video/webcams.mp4 got 8.71MiB / 117.32MiB
video/webcams.mp4 got 9.53MiB / 117.32MiB
video/webcams.mp4 got 10.31MiB / 117.32MiB
video/webcams.mp4 got 11.09MiB / 117.32MiB
video/webcams.mp4 got 11.87MiB / 117.32MiB
video/webcams.mp4 got 12.67MiB / 117.32MiB
video/webcams.mp4 got 13.45MiB / 117.32MiB
video/webcams.mp4 got 14.23MiB / 117.32MiB
video/webcams.mp4 got 15.02MiB / 117.32MiB
video/webcams.mp4 got 15.80MiB / 117.32MiB
video/webcams.mp4 got 16.60MiB / 117.32MiB
video/webcams.mp4 got 17.40MiB / 117.32MiB
video/webcams.mp4 got 18.20MiB / 117.32MiB
video/webcams.mp4 got 18.98MiB / 117.32MiB
video/webcams.mp4 got 19.77MiB / 117.32MiB
video/webcams.mp4 got 20.56MiB / 117.32MiB
video/webcams.mp4 got 21.34MiB / 117.32MiB
video/webcams.mp4 got 22.12MiB / 117.32MiB
video/webcams.mp4 got 22.91MiB / 117.32MiB
video/webcams.mp4 got 23.70MiB / 117.32MiB
video/webcams.mp4 got 24.49MiB / 117.32MiB
video/webcams.mp4 got 25.28MiB / 117.32MiB
video/webcams.mp4 got 26.06MiB / 117.32MiB
video/webcams.mp4 got 26.84MiB / 117.32MiB
video/webcams.mp4 got 27.62MiB / 117.32MiB
video/webcams.mp4 got 28.42MiB / 117.32MiB
video/webcams.mp4 got 29.22MiB / 117.32MiB
video/webcams.mp4 got 30.01MiB / 117.32MiB
video/webcams.mp4 got 30.79MiB / 117.32MiB
video/webcams.mp4 got 31.57MiB / 117.32MiB
video/webcams.mp4 got 32.37MiB / 117.32MiB
video/webcams.mp4 got 33.16MiB / 117.32MiB
video/webcams.mp4 got 33.94MiB / 117.32MiB
video/webcams.mp4 got 34.72MiB / 117.32MiB
video/webcams.mp4 got 35.50MiB / 117.32MiB
video/webcams.mp4 got 36.28MiB / 117.32MiB
video/webcams.mp4 got 37.08MiB / 117.32MiB
video/webcams.mp4 got 37.87MiB / 117.32MiB
video/webcams.mp4 got 38.66MiB / 117.32MiB
video/webcams.mp4 got 39.44MiB / 117.32MiB
video/webcams.mp4 got 40.23MiB / 117.32MiB
video/webcams.mp4 got 41.02MiB / 117.32MiB
video/webcams.mp4 got 41.81MiB / 117.32MiB
video/webcams.mp4 got 42.59MiB / 117.32MiB
video/webcams.mp4 got 43.39MiB / 117.32MiB
video/webcams.mp4 got 44.17MiB / 117.32MiB
video/webcams.mp4 got 45.01MiB / 117.32MiB
video/webcams.mp4 got 45.84MiB / 117.32MiB
video/webcams.mp4 got 46.62MiB / 117.32MiB
video/webcams.mp4 got 47.40MiB / 117.32MiB
video/webcams.mp4 got 48.20MiB / 117.32MiB
video/webcams.mp4 got 48.98MiB / 117.32MiB
video/webcams.mp4 got 49.76MiB / 117.32MiB
video/webcams.mp4 got 50.54MiB / 117.32MiB
video/webcams.mp4 got 51.32MiB / 117.32MiB
video/webcams.mp4 got 52.10MiB / 117.32MiB
video/webcams.mp4 got 52.91MiB / 117.32MiB
video/webcams.mp4 got 53.70MiB / 117.32MiB
video/webcams.mp4 got 54.51MiB / 117.32MiB
video/webcams.mp4 got 55.29MiB / 117.32MiB
video/webcams.mp4 got 56.09MiB / 117.32MiB
video/webcams.mp4 got 56.87MiB / 117.32MiB
video/webcams.mp4 got 57.65MiB / 117.32MiB
video/webcams.mp4 got 58.43MiB / 117.32MiB
video/webcams.mp4 got 59.21MiB / 117.32MiB
video/webcams.mp4 got 59.99MiB / 117.32MiB
video/webcams.mp4 got 60.78MiB / 117.32MiB
video/webcams.mp4 got 61.60MiB / 117.32MiB
video/webcams.mp4 got 62.42MiB / 117.32MiB
video/webcams.mp4 got 63.22MiB / 117.32MiB
video/webcams.mp4 got 64.02MiB / 117.32MiB
video/webcams.mp4 got 64.82MiB / 117.32MiB
video/webcams.mp4 got 65.66MiB / 117.32MiB
video/webcams.mp4 got 66.45MiB / 117.32MiB
video/webcams.mp4 got 67.25MiB / 117.32MiB
video/webcams.mp4 got 68.03MiB / 117.32MiB
video/webcams.mp4 got 68.82MiB / 117.32MiB
video/webcams.mp4 got 69.61MiB / 117.32MiB
video/webcams.mp4 got 70.39MiB / 117.32MiB
video/webcams.mp4 got 71.19MiB / 117.32MiB
video/webcams.mp4 got 71.98MiB / 117.32MiB
video/webcams.mp4 got 72.76MiB / 117.32MiB
video/webcams.mp4 got 73.54MiB / 117.32MiB
video/webcams.mp4 got 74.32MiB / 117.32MiB
video/webcams.mp4 got 75.12MiB / 117.32MiB
video/webcams.mp4 got 75.90MiB / 117.32MiB
video/webcams.mp4 got 76.70MiB / 117.32MiB
video/webcams.mp4 got 77.48MiB / 117.32MiB
video/webcams.mp4 got 78.26MiB / 117.32MiB
video/webcams.mp4 got 79.04MiB / 117.32MiB
video/webcams.mp4 got 79.82MiB / 117.32MiB
video/webcams.mp4 got 80.60MiB / 117.32MiB
video/webcams.mp4 got 81.40MiB / 117.32MiB
video/webcams.mp4 got 82.18MiB / 117.32MiB
video/webcams.mp4 got 82.97MiB / 117.32MiB
video/webcams.mp4 got 83.75MiB / 117.32MiB
video/webcams.mp4 got 84.57MiB / 117.32MiB
video/webcams.mp4 got 85.37MiB / 117.32MiB
video/webcams.mp4 got 86.16MiB / 117.32MiB
video/webcams.mp4 got 86.94MiB / 117.32MiB
video/webcams.mp4 got 87.72MiB / 117.32MiB
video/webcams.mp4 got 88.50MiB / 117.32MiB
video/webcams.mp4 got 89.28MiB / 117.32MiB
video/webcams.mp4 got 90.06MiB / 117.32MiB
video/webcams.mp4 got 90.84MiB / 117.32MiB
video/webcams.mp4 got 91.65MiB / 117.32MiB
video/webcams.mp4 got 92.46MiB / 117.32MiB
video/webcams.mp4 got 93.24MiB / 117.32MiB
video/webcams.mp4 got 94.03MiB / 117.32MiB
video/webcams.mp4 got 94.83MiB / 117.32MiB
video/webcams.mp4 got 95.61MiB / 117.32MiB
video/webcams.mp4 got 96.39MiB / 117.32MiB
video/webcams.mp4 got 97.17MiB / 117.32MiB
video/webcams.mp4 got 97.96MiB / 117.32MiB
video/webcams.mp4 got 98.77MiB / 117.32MiB
video/webcams.mp4 got 99.56MiB / 117.32MiB
video/webcams.mp4 got 100.37MiB / 117.32MiB
video/webcams.mp4 got 101.15MiB / 117.32MiB
video/webcams.mp4 got 101.93MiB / 117.32MiB
video/webcams.mp4 got 102.71MiB / 117.32MiB
video/webcams.mp4 got 103.49MiB / 117.32MiB
video/webcams.mp4 got 104.28MiB / 117.32MiB
video/webcams.mp4 got 105.06MiB / 117.32MiB
video/webcams.mp4 got 105.84MiB / 117.32MiB
video/webcams.mp4 got 106.62MiB / 117.32MiB
video/webcams.mp4 got 107.42MiB / 117.32MiB
video/webcams.mp4 got 108.21MiB / 117.32MiB
video/webcams.mp4 got 108.99MiB / 117.32MiB
video/webcams.mp4 got 109.80MiB / 117.32MiB
video/webcams.mp4 got 110.58MiB / 117.32MiB
video/webcams.mp4 got 111.38MiB / 117.32MiB
video/webcams.mp4 got 112.23MiB / 117.32MiB
video/webcams.mp4 got 113.03MiB / 117.32MiB
video/webcams.mp4 got 113.81MiB / 117.32MiB
video/webcams.mp4 got 114.59MiB / 117.32MiB
video/webcams.mp4 got 115.40MiB / 117.32MiB
video/webcams.mp4 got 116.20MiB / 117.32MiB
video/webcams.mp4 got 116.98MiB / 117.32MiB
Successfully downloaded video/webcams.mp4
Downloading slides
Downloading presentation/4f471951b3e1b56728227e7fd724ab7147c11f27-1721147205124/slide-1.png...
Downloading presentation/4f471951b3e1b56728227e7fd724ab7147c11f27-1721147205124/slide-2.png...
Downloading presentation/4f471951b3e1b56728227e7fd724ab7147c11f27-1721147205124/slide-3.png...
presentation/4f471951b3e1b56728227e7fd724ab7147c11f27-1721147205124/slide-1.png got 10.00KiB / 50.14KiB
presentation/4f471951b3e1b56728227e7fd724ab7147c11f27-1721147205124/slide-3.png got 10.00KiB / 40.96KiB
Successfully downloaded presentation/4f471951b3e1b56728227e7fd724ab7147c11f27-1721147205124/slide-1.png
Successfully downloaded presentation/4f471951b3e1b56728227e7fd724ab7147c11f27-1721147205124/slide-3.png
presentation/4f471951b3e1b56728227e7fd724ab7147c11f27-1721147205124/slide-2.png got 10.00KiB / 48.14KiB
Successfully downloaded presentation/4f471951b3e1b56728227e7fd724ab7147c11f27-1721147205124/slide-2.png
Recording title: 16 Temmuz / Vocabulary
Recording date: 2024-07-16T19-26-20
Recording duration: 1:31:03
No desk was shared in this session
Start capturing frames...
Output directory for frames is: C:\Users\eneso\AppData\Local\bbb-dl\7a6c36684e75ca32a09f13155137294b\frames
Initialization takes a few seconds...

Done: 00011 / 03052 Frames | 000 / 009 Parts /
1/9 Partition finished: 1:27:01 to 1:27:01

2/9 Partition finished: 54:56 to 54:59

3/9 Partition finished: 54:54 to 54:56

4/9 Partition finished: 1:27:08 to 1:27:12

5/9 Partition finished: 1:27:12 to 2:05:29
Done: 00058 / 03052 Frames | 005 / 009 Parts |
6/9 Partition finished: 1:27:01 to 1:27:08
Done: 00129 / 03052 Frames | 006 / 009 Parts -
7/9 Partition finished: 1:24:10 to 1:27:01
Done: 02344 / 03052 Frames | 007 / 009 Parts /
8/9 Partition finished: 54:59 to 1:24:10
Done: 03040 / 03052 Frames | 008 / 009 Parts \
9/9 Partition finished: 0 to 54:54

Frames capturing is finished and took: 2:24.
Start creating slideshow...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\eneso\Desktop\videolar\venv\Scripts\bbb-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\eneso\Desktop\videolar\venv\Lib\site-packages\bbb_dl\main.py", line 1521, in main
    bbb_dl.run()
  File "C:\Users\eneso\Desktop\videolar\venv\Lib\site-packages\bbb_dl\main.py", line 280, in run
    slideshow_path = self.create_slideshow(frames)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eneso\Desktop\videolar\venv\Lib\site-packages\bbb_dl\main.py", line 1259, in create_slideshow
    asyncio.run(self.ffmpeg.create_slideshow(slideshow_txt_path, slideshow_path))
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\eneso\Desktop\videolar\venv\Lib\site-packages\bbb_dl\ffmpeg.py", line 194, in create_slideshow
    await ffmpeg.execute()
  File "C:\Users\eneso\Desktop\videolar\venv\Lib\site-packages\ffmpeg\asyncio\ffmpeg.py", line 177, in execute
    self._process = await create_subprocess(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\asyncio\subprocess.py", line 224, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1743, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 400, in _make_subprocess_transport
    transp = _WindowsSubprocessTransport(self, protocol, args, shell,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 878, in _start
    self._proc = windows_utils.Popen(
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_utils.py", line 153, in __init__
    super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by C0D3D3V** [comment]
Haha, yes, next time please send the whole log directly. Then we could have saved ourselves the lively exchange of messages.

As you can see at the end of your log, there is the real error. 

:/ Windows problem. Will take some time probably till I can fix it. 


What windows version are you using?

Can you make a second run and add the option `--verbose`? And then send the complete log again.

**Comment by C0D3D3V** [comment]
There also seems to be something wrong with your bbb-dl installation. Is your installation new, or have you installed it for long time?

Could you please try to update bbb-dl?
like: `pip install -U bbb-dl`

**Comment by EnesOz1** [comment]
> Haha, yes, next time please send the whole log directly. Then we could have saved ourselves the lively exchange of messages.
> 
> As you can see at the end of your log, there is the real error.
> 
> :/ Windows problem. Will take some time probably till I can fix it.
> 
> What windows version are you using?
> 
> Can you make a second run and add the option `--verbose`? And then send the complete log again.

Sorry mate i am not good at this i am just learning to improve myself and sorry for taking your time.
I am using Windows 10 Pro 22H2

(venv) C:\Users\eneso\Desktop\videolar>bbb-dl --verbose https://canliders.kemalhoca.com/playback/presentation/2.3/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119
Output directory for the final video is: C:\Users\eneso\Desktop\videolar
Directory for the temporary files is: C:\Users\eneso\AppData\Local\bbb-dl\7a6c36684e75ca32a09f13155137294b
Downloading meta information
metadata.xml is already present
shapes.svg is already present
Downloading webcams / deskshare
cursor.xml is already present
panzooms.xml is already present
captions.json is already present
deskshare.xml is already present
Downloading events.xml from: https://canliders.kemalhoca.com/presentation/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119/events.xml
presentation_text.json is already present
slides_new.xml is already present
Downloading notes.html from: https://canliders.kemalhoca.com/presentation/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119/notes.html
Downloading polls.json from: https://canliders.kemalhoca.com/presentation/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119/polls.json
Downloading external_videos.json from: https://canliders.kemalhoca.com/presentation/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119/external_videos.json
Downloading video/webcams.webm from: https://canliders.kemalhoca.com/presentation/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119/video/webcams.webm
video/webcams.mp4 is already present
Downloading deskshare/deskshare.webm from: https://canliders.kemalhoca.com/presentation/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119/deskshare/deskshare.webm
Downloading deskshare/deskshare.mp4 from: https://canliders.kemalhoca.com/presentation/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119/deskshare/deskshare.mp4
external_videos.json could not be downloaded: 404 Not Found
Error: 404, message='Not Found', url='https://canliders.kemalhoca.com/presentation/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119/external_videos.json'
events.xml could not be downloaded: 404 Not Found
Error: 404, message='Not Found', url='https://canliders.kemalhoca.com/presentation/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119/events.xml'
polls.json could not be downloaded: 404 Not Found
Error: 404, message='Not Found', url='https://canliders.kemalhoca.com/presentation/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119/polls.json'
notes.html could not be downloaded: 404 Not Found
Error: 404, message='Not Found', url='https://canliders.kemalhoca.com/presentation/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119/notes.html'
video/webcams.webm could not be downloaded: 404 Not Found
Error: 404, message='Not Found', url='https://canliders.kemalhoca.com/presentation/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119/video/webcams.webm'
deskshare/deskshare.webm could not be downloaded: 404 Not Found
Error: 404, message='Not Found', url='https://canliders.kemalhoca.com/presentation/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119/deskshare/deskshare.webm'
deskshare/deskshare.mp4 could not be downloaded: 404 Not Found
Error: 404, message='Not Found', url='https://canliders.kemalhoca.com/presentation/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119/deskshare/deskshare.mp4'
Downloading slides
presentation/4f471951b3e1b56728227e7fd724ab7147c11f27-1721147205124/slide-1.png is already present
presentation/4f471951b3e1b56728227e7fd724ab7147c11f27-1721147205124/slide-2.png is already present
presentation/4f471951b3e1b56728227e7fd724ab7147c11f27-1721147205124/slide-3.png is already present
Recording title: 16 Temmuz / Vocabulary
Recording date: 2024-07-16T19-26-20
Recording duration: 1:31:03
BBB version: 3.11.11+
No desk was shared in this session
Start capturing frames...
Output directory for frames is: C:\Users\eneso\AppData\Local\bbb-dl\7a6c36684e75ca32a09f13155137294b\frames
Initialization takes a few seconds...

Done: 00000 / 10168 Frames | 000 / 009 Parts /
1/9 Partition already finished: 1:27:01 to 1:27:01
Done: 00053 / 10168 Frames | 001 / 009 Parts /
2/9 Partition finished: 54:54 to 54:56

3/9 Partition finished: 54:56 to 54:59

4/9 Partition finished: 1:27:08 to 1:27:12
Done: 00198 / 10168 Frames | 004 / 009 Parts \
5/9 Partition finished: 1:27:01 to 1:27:08

6/9 Partition finished: 1:27:12 to 2:05:29
Done: 01194 / 10168 Frames | 006 / 009 Parts \
7/9 Partition finished: 1:24:10 to 1:27:01
Done: 07814 / 10168 Frames | 007 / 009 Parts \
8/9 Partition finished: 54:59 to 1:24:10
Done: 10157 / 10168 Frames | 008 / 009 Parts -
9/9 Partition finished: 0 to 54:54

Frames capturing is finished and took: 5:17.
Start creating slideshow...
Running command: ffmpeg -hide_banner -f concat -i C:\Users\eneso\AppData\Local\bbb-dl\7a6c36684e75ca32a09f13155137294b\frames\slideshow.txt -c:v libx264 -c:a copy -framerate 24 -r 24 -pix_fmt yuv420p -strict experimental -crf 23 -preset fast C:\Users\eneso\AppData\Local\bbb-dl\7a6c36684e75ca32a09f13155137294b\slideshow.mp4
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\eneso\Desktop\videolar\venv\Scripts\bbb-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\eneso\Desktop\videolar\venv\Lib\site-packages\bbb_dl\main.py", line 1521, in main
    bbb_dl.run()
  File "C:\Users\eneso\Desktop\videolar\venv\Lib\site-packages\bbb_dl\main.py", line 280, in run
    slideshow_path = self.create_slideshow(frames)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eneso\Desktop\videolar\venv\Lib\site-packages\bbb_dl\main.py", line 1259, in create_slideshow
    asyncio.run(self.ffmpeg.create_slideshow(slideshow_txt_path, slideshow_path))
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\eneso\Desktop\videolar\venv\Lib\site-packages\bbb_dl\ffmpeg.py", line 194, in create_slideshow
    await ffmpeg.execute()
  File "C:\Users\eneso\Desktop\videolar\venv\Lib\site-packages\ffmpeg\asyncio\ffmpeg.py", line 177, in execute
    self._process = await create_subprocess(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\asyncio\subprocess.py", line 224, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1743, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 400, in _make_subprocess_transport
    transp = _WindowsSubprocessTransport(self, protocol, args, shell,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 878, in _start
    self._proc = windows_utils.Popen(
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_utils.py", line 153, in __init__
    super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\eneso\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] System cannot found specified file

**Comment by EnesOz1** [comment]
> There also seems to be something wrong with your bbb-dl installation. Is your installation new, or have you installed it for long time?
> 
> Could you please try to update bbb-dl? like: `pip install -U bbb-dl`

I just installed new

**Comment by C0D3D3V** [comment]
Have you installed ffmpeg correct? Have you restarted (or re-login) after installation of ffmpeg?

**Comment by EnesOz1** [comment]
> Have you installed ffmpeg correct? Have you restarted (or re-login) after installation of ffmpeg?

Maybe it's the reason because i am not sure i've installed correctly ffmpeg 
how am i be sure installed correctly or how can i install

**Comment by C0D3D3V** [comment]
Don't worry, I'm doing it voluntarily, you're not wasting my time. I meant it as a joke, but so that you can do better in the future.


Normally bbb-dl should detect if ffmpeg is missing. But maybe this part is broken. I will check it the next days.

For now you could just place the ffmpeg.exe in the same folder where you run your comand. And use the option to specify the location of ffmpeg. You will find the option if you run `bbb-dl --help`

**Comment by C0D3D3V** [comment]
The option is `--ffmpeg-location`
Use it like `--ffmpeg-location .` if the ffmpeg exe is in the same direcotry as you run the command
or like `--ffmpeg-location C:\\Path\to\ffmpeg\` if you want to specify the directory in that the ffmpeg.exe is

**Comment by EnesOz1** [comment]
> Don't worry, I'm doing it voluntarily, you're not wasting my time. I meant it as a joke, but so that you can do better in the future.
> 
> Normally bbb-dl should detect if ffmpeg is missing. But maybe this part is broken. I will check it the next days.
> 
> For now you could just place the ffmpeg.exe in the same folder where you run your comand. And use the option to specify the location of ffmpeg. You will find the option if you run `bbb-dl --help`

![image](https://github.com/user-attachments/assets/6a6d503d-2d75-456a-b293-8bf047181e86)
Like this you saying?

**Comment by C0D3D3V** [comment]
Yes, thats an option. Place ffprobe.exe in there too. Thats needed too.

**Comment by EnesOz1** [comment]
> The option is `--ffmpeg-location` Use it like `--ffmpeg-location .` if the ffmpeg exe is in the same direcotry as you run the command or like `--ffmpeg-location C:\\Path\to\ffmpeg\` if you want to specify the directory in that the ffmpeg.exe is

i run --help command and i saw ffmpeg location

**Comment by C0D3D3V** [comment]
then add this option to your bbb-dl command

**Comment by EnesOz1** [comment]
> --ffmpeg-location

(venv) C:\Users\eneso\Desktop\videolar>bbb-dl --ffmpeg-location https://canliders.kemalhoca.com/playback/presentation/2.3/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119
usage: bbb-dl [-h] [-ao] [-sw] [-swfd] [-sa] [-sc] [-sz] [-bk] [-kt] [-v] [--ffmpeg-location FFMPEG_LOCATION] [-scv]
              [-ais] [-uac] [-ftv FORCE_TLS_VERSION] [--version] [--encoder ENCODER] [--audiocodec AUDIOCODEC]
              [--preset PRESET] [--crf CRF] [-f FILENAME] [-od OUTPUT_DIR] [-wd WORKING_DIR]
              [-mpc MAX_PARALLEL_CHROMES] [-fw FORCE_WIDTH] [-fh FORCE_HEIGHT]
              URL
bbb-dl: error: the following arguments are required: URL

**Comment by C0D3D3V** [comment]
You have to specify the path to the directory after the `--ffmpeg-location` option. As I explained above.

Like 
`bbb-dl --ffmpeg-location C:\Users\eneso\Desktop\Path\To\FFMPEG-Folder https://canliders.kemalhoca.com/playback/presentation/2.3/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119`

**Comment by EnesOz1** [comment]
> You have to specify the path to the directory after the `--ffmpeg-location` option. As I explained above.
> 
> Like `bbb-dl --ffmpeg-location C:\Users\eneso\Desktop\Path\To\FFMPEG-Folder https://canliders.kemalhoca.com/playback/presentation/2.3/7ed0acd086a0b7a637466274d98fac848326fd88-1721147180119`

Sorry for the late reply, i did it thank you so much. 
But do you have advice for the speed up the creating slideshow

**Comment by C0D3D3V** [comment]
If you have a graphic card you can speed up the process a lot (like up to 100x depending on your graphic card)
See the readme for details, and ask if you still have questions.

**Comment by EnesOz1** [comment]
> If you have a graphic card you can speed up the process a lot (like up to 100x depending on your graphic card) See the readme for details, and ask if you still have questions.

Thanks for your help again, have a nice day.
