### ISSUE TITLE
Change output filename

### ISSUE THREAD

**Issue by persuader** [C0D3D3V/bbb-dl#8]
Hi. Thanks for the good work - the tool is real gem as it does not rely on chromium. I have one question.

Can i use metadata->bbb-context instead of metadata->meetingName for naming of the output files ? It will be good to have ouput filename as command line parameter.

**Comment by C0D3D3V** [comment]
Sounds like a nice feature. You are welcome to implement it and make a pull request :)

**Comment by persuader** [comment]
#9
